### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Gu-Youngfeng** [Gu-Youngfeng/BehaviorDection#2]
When running the `cstar.yongfeng.collect.Launcher` to get the metrics of each userZip, an unexpected exception occurs. The stack trace is as follows,

```java
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at com.google.gson.internal.LinkedTreeMap.<init>(LinkedTreeMap.java:52)
	at com.google.gson.internal.LinkedTreeMap.<init>(LinkedTreeMap.java:60)
	at com.google.gson.JsonObject.<init>(JsonObject.java:33)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:664)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:667)
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642)
	at com.google.gson.internal.Streams.parse(Streams.java:44)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:239)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at cc.kave.commons.utils.io.json.JsonUtils.fromJson(JsonUtils.java:362)
	at cc.kave.commons.utils.io.json.JsonUtils.fromJson(JsonUtils.java:396)
	at cc.kave.commons.utils.io.ReadingArchive.getNext(ReadingArchive.java:63)
	at cstar.yongfeng.collect.Collector.miningWork(Collector.java:149)
```

I also noticed that when the userZip's size is much large (**Over 50M**), the exception is likely to occur, when the userZip's size is much small (**Less than 10M**), the exception will not be thrown.

**Comment by Gu-Youngfeng** [comment]
Yeah, you're probably right. The large size of userZip results in this **OutOfMemoryError** exception. Maybe we should do some optimal work on the Java code to reduce the memory overheads right now. 

Some possible related solutions include [GC overhead limit exceeded](http://blog.csdn.net/renfufei/article/details/77585294), and [Java heap space](http://blog.csdn.net/renfufei/article/details/76350794).

**Comment by Gu-Youngfeng** [comment]
I have done some fixing works for the project, but it fails again. Like that, 

```java
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.google.gson.stream.JsonReader.<init>(JsonReader.java:238)
	at com.google.gson.internal.bind.JsonTreeReader.<init>(JsonTreeReader.java:53)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:280)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.TypeAdapter.fromJsonTree(TypeAdapter.java:281)
	at cc.kave.commons.utils.io.json.RuntimeTypeAdapterFactory$1.read(RuntimeTypeAdapterFactory.java:254)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at cc.kave.commons.utils.io.json.JsonUtils.fromJson(JsonUtils.java:362)
	at cc.kave.commons.utils.io.json.JsonUtils.fromJson(JsonUtils.java:396)
	at cc.kave.commons.utils.io.ReadingArchive.getNext(ReadingArchive.java:63)
	at cstar.yongfeng.collect.Collector.miningWork(Collector.java:147)
	at cstar.yongfeng.collect.Collector.Collecting(Collector.java:70)
	at cstar.yongfeng.collect.Collector.<init>(Collector.java:41)
	at cstar.yongfeng.collect.UsageGetter.<init>(UsageGetter.java:33)
	at cstar.yongfeng.collect.Launcher.DoWorks(Launcher.java:78)
	at cstar.yongfeng.collect.Launcher.main(Launcher.java:66)
```

**Comment by Gu-Youngfeng** [comment]
Through the **stack traces** given by the Eclipse, I almost get the root cause of this **OutOfMemoryError**. Because the total number of events to be handled is over **11,000,000** (11M), then for each developer, we also need to handle **135,000** (13.5K) events on average. 

When handling the event stream, I first visit each event and save it as a node object (contains its triggered time, operation information , etc.), then I collect the same type (Debugging, Working, etc.) of events into a stream list. But if the type appears much less than we excpected, then the size of the stream list can be very large, up to the upper bound  of Java heap size, and the **OutOfMemoryError** happens.

More specific, when calculating the In-IDE time of developers, I use the tag `Startup` / `Shutdown` of **[IDEStateEvent]** to detect this In-IDE time, and save all the events between the `Startup` and `Shutdown` into a event list. And this might result in thousands and tens of thousands of events in one event list, considering the size of one event, this thousands and tens of thousands of events can easily cause the GC exception or the Java heap exception.
